title: Machine Learning Applied for Speech
subtitle: UEF Summer School 2023
url: "https://vpspeech.github.io"
subtitle_url: "http://www.uef.fi/en/web/summerschool/machine-learning-for-speech"
baseurl: "/temp1.github.io"

markdown: kramdown

google_analytics: UA-119760540-1

sass:
    style: compressed
    sass_dir: _sass
